<?php

function businessgoa_menu() {

	$common = array ('menu_name' => 'primary-links', 'page callback' => 'show_bg_section', 'page arguments' => array (1 ) );

	$items ['home'] = array ('page callback' => 'bg_home', 'access callback' => TRUE );
	$items ['bon-appetit'] = $common;
	$items ['book-shelf'] = $common;
	$items ['cover-story'] = $common;
	$items ['editorial'] = $common;
	$items ['family-business'] = $common;
	$items ['goan-brand'] = $common;
	$items ['green-goa'] = $common;
	$items ['in-focus'] = $common;
	$items ['interview'] = $common;
	$items ['legal-eagle'] = $common;
	$items ['letters-to-the-editor'] = $common;
	$items ['love-for-business'] = $common;
	$items ['money-and-markets'] = $common;
	$items ['news'] = $common;
	$items ['newsmakers'] = $common;
	$items ['professional-dossier'] = $common;
	$items ['starting-young'] = $common;
	$items ['thinking-hat'] = $common;
	$items ['uncommon-wealth'] = $common;

	return $items;
}

function get_latest_page_from_section($section) {

	$section_id = current ( taxonomy_get_term_by_name ( $section ) )->tid;
	$month = time () + 60 * 60 * 24 * 30;
	do {
		$month -= 60 * 60 * 24 * 30;
		$month_id = @current ( taxonomy_get_term_by_name ( date ( 'F Y', $month ) ) )->tid;
		if (! $month_id)
			continue;
		$articles = taxonomy_select_nodes ( array ($section_id, $month_id ), 'and' );
	} while ( is_null ( $articles ) or mysqli_num_rows ( $articles ) == 0 );
	return node_load ( mysqli_fetch_object ( $articles )->nid );
}

function businessgoa_block($op = 'list', $delta = 0, $edit = array()) {
	switch ($op) {
		case 'list' :
			$blocks [0] ['info'] = t ( 'Editorial' );
			$blocks [0] ['title'] = 'Editorial';
			$blocks [0] ['pages'] = '<front>';
			$blocks [0] ['cache'] = BLOCK_CACHE_GLOBAL;
			$blocks [0] ['region'] = 'bottom_left_region';
			$blocks [0] ['custom'] = true;
			$blocks [0] ['status'] = true;

			$blocks [1] ['info'] = t ( 'In Focus' );
			$blocks [1] ['title'] = 'In Focus';
			$blocks [1] ['pages'] = '<front>';
			$blocks [1] ['cache'] = BLOCK_CACHE_GLOBAL;
			$blocks [1] ['region'] = 'bottom_mid_region';
			$blocks [1] ['custom'] = true;
			$blocks [1] ['status'] = true;

			$blocks [2] ['info'] = t ( 'Starting Young' );
			$blocks [2] ['title'] = 'Starting Young';
			$blocks [2] ['pages'] = '<front>';
			$blocks [2] ['cache'] = BLOCK_CACHE_GLOBAL;
			$blocks [2] ['region'] = 'bottom_right_region';
			$blocks [2] ['custom'] = true;
			$blocks [2] ['status'] = true;

			$blocks [3] ['info'] = t ( 'Goan Brand' );
			$blocks [3] ['title'] = 'Goan Brand';
			$blocks [3] ['pages'] = '<front>';
			$blocks [3] ['cache'] = BLOCK_CACHE_GLOBAL;
			$blocks [3] ['region'] = 'side_upper_region';
			$blocks [3] ['custom'] = true;
			$blocks [3] ['status'] = true;

			$blocks [4] ['info'] = t ( 'Interview' );
			$blocks [4] ['title'] = 'Interview';
			$blocks [4] ['pages'] = '<front>';
			$blocks [4] ['cache'] = BLOCK_CACHE_GLOBAL;
			$blocks [4] ['region'] = 'side_mid_region';
			$blocks [4] ['custom'] = true;
			$blocks [4] ['status'] = true;

			$blocks [5] ['info'] = t ( 'Bon Appetit' );
			$blocks [5] ['title'] = 'Bon Appetit';
			$blocks [5] ['pages'] = '<front>';
			$blocks [5] ['cache'] = BLOCK_CACHE_GLOBAL;
			$blocks [5] ['region'] = 'side_lower_region';
			$blocks [5] ['custom'] = true;
			$blocks [5] ['status'] = true;

			$blocks [6] ['info'] = t ( 'Facebook Fans' );
			$blocks [6] ['title'] = 'Facebook Fans';
			$blocks [6] ['pages'] = '<front>';
			$blocks [6] ['cache'] = BLOCK_CACHE_GLOBAL;
			$blocks [6] ['region'] = 'side_upper_region';
			$blocks [6] ['custom'] = true;
			$blocks [6] ['status'] = true;

			$blocks [7] ['info'] = t ( 'Facebook Comments' );
			$blocks [7] ['title'] = 'Facebook Comments';
			$blocks [7] ['pages'] = '<front>';
			$blocks [7] ['cache'] = BLOCK_CACHE_GLOBAL;
			$blocks [7] ['region'] = 'below_content_region';
			$blocks [7] ['custom'] = true;
			$blocks [7] ['status'] = true;

			return $blocks;
		case 'view' :
			switch ($delta) {
				case 0 :
					$content = get_latest_page_from_section ( 'Editorial' );
					$block ['subject'] = l ( t ( 'Editorial' ), $content->path );
					$block ['content'] = $content->teaser . '<br>' . l ( 'Read more', $content->path );
					break;
				case 1 :
					$content = get_latest_page_from_section ( 'In Focus' );
					$block ['subject'] = l ( t ( 'In Focus' ), $content->path );
					$block ['content'] = $content->teaser . '<br>' . l ( 'Read more', $content->path );
					break;
				case 2 :
					$content = get_latest_page_from_section ( 'Starting Young' );
					$block ['subject'] = l ( t ( 'Starting Young' ), $content->path );
					$block ['content'] = $content->teaser . '<br>' . l ( 'Read more', $content->path );
					break;
				case 3 :
					$content = get_latest_page_from_section ( 'Goan Brand' );
					$block ['subject'] = l ( t ( 'Goan Brand' ), $content->path );
					$block ['content'] = $content->teaser . '<br>' . l ( 'Read more', $content->path );
					break;
				case 4 :
					$content = get_latest_page_from_section ( 'Interview' );
					$block ['subject'] = l ( t ( 'Interview' ), $content->path );
					$block ['content'] = $content->teaser . '<br>' . l ( 'Read more', $content->path );
					break;
				case 5 :
					$content = get_latest_page_from_section ( 'Bon Appetit' );
					$block ['subject'] = l ( t ( 'Bon Appetit' ), $content->path );
					$block ['content'] = $content->teaser . '<br>' . l ( 'Read more', $content->path );
					break;
				case 6 :
					$block ['subject'] = 'Facebook Like';
					$block ['content'] = "<fb:like-box profile_id='121764281183650' width='170' stream='false' header='false'></fb:like-box>";
					break;
				case 7 :
					$block ['subject'] = 'Facebook Comments';
					$block ['content'] = "<fb:comments></fb:comments>";
					break;
			}
			return $block;
	}
	return $op->content;
}

function bg_home() {
	return get_latest_page_from_section ( 'Cover Story' )->teaser;
}