<?php

function businessgoa_menu() {

	$common = array ('page callback' => 'bg_section', 'page arguments' => array (0 ), 'access callback' => TRUE );

	$items ['home'] = array ('page callback' => 'bg_archives', 'access callback' => TRUE );
	$items ['etc'] = array ('page callback' => 'bg_etc', 'access callback' => TRUE );
	$items ['gallery'] = array ('page callback' => 'bg_gallery', 'access callback' => TRUE );
	$items ['aboutus'] = array ('page callback' => 'bg_about', 'access callback' => TRUE );
	$items ['archives'] = array ('page callback' => 'bg_archivelist', 'access callback' => TRUE );
	$items ['archives/%'] = array ('page callback' => 'bg_archives', 'access callback' => TRUE, 'page arguments' => array (1 ) );

	$items ['Bon-Appetit'] = $common;
	$items ['Book-Shelf'] = $common;
	$items ['Cover-Story'] = $common;
	$items ['Editorial'] = $common;
	$items ['Family-Business'] = $common;
	$items ['Goan-Brand'] = $common;
	$items ['Green-Goa'] = $common;
	$items ['In-Focus'] = $common;
	$items ['Interview'] = $common;
	$items ['Legal-Eagle'] = $common;
	$items ['Love-For-Business'] = $common;
	$items ['Money-And-Markets'] = $common;
	$items ['Out-of-the-Box'] = $common;
	$items ['Professional-Dossier'] = $common;
	$items ['Starting-Young'] = $common;
	$items ['Story-of-Enterprise'] = $common;
	$items ['Thinking-Hat'] = $common;
	$items ['Uncommon-Wealth'] = $common;

	return $items;
}

function bg_get_article($section, $month = false) {
	$section_id = current ( taxonomy_get_term_by_name ( $section ) )->tid;
	$month = ($month ? strtotime ( $month ) : time ()) + 60 * 60 * 24 * 30;
	do {
		$month -= 60 * 60 * 24 * 30;
		$month_id = @current ( taxonomy_get_term_by_name ( date ( 'F Y', $month ) ) )->tid;
		if (! $month_id)
			continue;
		$articles = taxonomy_select_nodes ( array ($section_id, $month_id ), 'and' );
		$test_fn = get_class ( $articles ) == 'mysqli_result' ? 'mysqli_num_rows' : 'mysql_num_rows';
	} while ( is_null ( $articles ) or call_user_func ( $test_fn, $articles ) == 0 );
	$test_fn = get_class ( $articles ) == 'mysqli_result' ? 'mysqli_fetch_object' : 'mysql_fetch_object';
	return node_load ( call_user_func ( $test_fn, $articles )->nid );
}

function businessgoa_block($op = 'list', $delta = 0, $edit = array()) {
	switch ($op) {
		case 'list' :
			$blocks [0] ['info'] = t ( 'Story of Enterprise' );
			$blocks [0] ['title'] = 'Story of Enterprise';
			$blocks [0] ['pages'] = '<front>';
			$blocks [0] ['cache'] = BLOCK_CACHE_GLOBAL;
			$blocks [0] ['region'] = 'bottom_left_region';
			$blocks [0] ['custom'] = true;
			$blocks [0] ['status'] = true;

			$blocks [1] ['info'] = t ( 'In Focus' );
			$blocks [1] ['title'] = 'In Focus';
			$blocks [1] ['pages'] = '<front>';
			$blocks [1] ['cache'] = BLOCK_CACHE_GLOBAL;
			$blocks [1] ['region'] = 'bottom_mid_region';
			$blocks [1] ['custom'] = true;
			$blocks [1] ['status'] = true;

			$blocks [2] ['info'] = t ( 'Starting Young' );
			$blocks [2] ['title'] = 'Starting Young';
			$blocks [2] ['pages'] = '<front>';
			$blocks [2] ['cache'] = BLOCK_CACHE_GLOBAL;
			$blocks [2] ['region'] = 'bottom_right_region';
			$blocks [2] ['custom'] = true;
			$blocks [2] ['status'] = true;

			$blocks [3] ['info'] = t ( 'Goan Brand' );
			$blocks [3] ['title'] = 'Goan Brand';
			$blocks [3] ['pages'] = '<front>';
			$blocks [3] ['cache'] = BLOCK_CACHE_GLOBAL;
			$blocks [3] ['region'] = 'side_upper_region';
			$blocks [3] ['custom'] = true;
			$blocks [3] ['status'] = true;

			$blocks [4] ['info'] = t ( 'Interview' );
			$blocks [4] ['title'] = 'Interview';
			$blocks [4] ['pages'] = '<front>';
			$blocks [4] ['cache'] = BLOCK_CACHE_GLOBAL;
			$blocks [4] ['region'] = 'side_mid_region';
			$blocks [4] ['custom'] = true;
			$blocks [4] ['status'] = true;

			$blocks [5] ['info'] = t ( 'Bon Appetit' );
			$blocks [5] ['title'] = 'Bon Appetit';
			$blocks [5] ['pages'] = '<front>';
			$blocks [5] ['cache'] = BLOCK_CACHE_GLOBAL;
			$blocks [5] ['region'] = 'side_lower_region';
			$blocks [5] ['custom'] = true;
			$blocks [5] ['status'] = true;

			$blocks [6] ['info'] = t ( 'Facebook Fans' );
			$blocks [6] ['title'] = 'Facebook Fans';
			$blocks [6] ['pages'] = '<front>';
			$blocks [6] ['cache'] = BLOCK_CACHE_GLOBAL;
			$blocks [6] ['region'] = 'side_upper_region';
			$blocks [6] ['custom'] = true;
			$blocks [6] ['status'] = true;

			$blocks [7] ['info'] = t ( 'Facebook Comments' );
			$blocks [7] ['title'] = 'Facebook Comments';
			$blocks [7] ['pages'] = '<front>';
			$blocks [7] ['cache'] = BLOCK_CACHE_GLOBAL;
			$blocks [7] ['region'] = 'below_content_region';
			$blocks [7] ['custom'] = true;
			$blocks [7] ['status'] = true;

			$blocks [8] ['info'] = t ( 'Previous Articles' );
			$blocks [8] ['title'] = 'Previous Articles';
			$blocks [8] ['pages'] = '<front>';
			$blocks [8] ['cache'] = BLOCK_CACHE_PER_PAGE;
			$blocks [8] ['region'] = 'side_mid_region';
			$blocks [8] ['custom'] = false;
			$blocks [8] ['status'] = true;

			$blocks [9] ['info'] = t ( 'Other Articles' );
			$blocks [9] ['title'] = 'Other Articles';
			$blocks [9] ['pages'] = '<front>';
			$blocks [9] ['cache'] = BLOCK_CACHE_PER_PAGE;
			$blocks [9] ['region'] = 'side_lower_region';
			$blocks [9] ['custom'] = false;
			$blocks [9] ['status'] = true;

			return $blocks;
		case 'view' :
			switch ($delta) {
				case 0 :
					$content = bg_get_article ( 'Story of Enterprise', next ( explode ( '/', $_GET ['q'] ) ) );
					$block ['subject'] = l ( t ( 'Story of Enterprise' ), $content->path );
					$block ['content'] = $content->teaser . '<br>' . l ( 'Read more', $content->path );
					break;
				case 1 :
					$content = bg_get_article ( 'In Focus', next ( explode ( '/', $_GET ['q'] ) ) );
					$block ['subject'] = l ( t ( 'In Focus' ), $content->path );
					$block ['content'] = $content->teaser . '<br>' . l ( 'Read more', $content->path );
					break;
				case 2 :
					$content = bg_get_article ( 'Starting Young', next ( explode ( '/', $_GET ['q'] ) ) );
					$block ['subject'] = l ( t ( 'Starting Young' ), $content->path );
					$block ['content'] = $content->teaser . '<br>' . l ( 'Read more', $content->path );
					break;
				case 3 :
					$content = bg_get_article ( 'Goan Brand', next ( explode ( '/', $_GET ['q'] ) ) );
					$block ['subject'] = l ( t ( 'Goan Brand' ), $content->path );
					$block ['content'] = $content->teaser . '<br>' . l ( 'Read more', $content->path );
					break;
				case 4 :
					$content = bg_get_article ( 'Interview', next ( explode ( '/', $_GET ['q'] ) ) );
					$block ['subject'] = l ( t ( 'Interview' ), $content->path );
					$block ['content'] = $content->teaser . '<br>' . l ( 'Read more', $content->path );
					break;
				case 5 :
					$content = bg_get_article ( 'Bon Appetit', next ( explode ( '/', $_GET ['q'] ) ) );
					$block ['subject'] = l ( t ( 'Bon Appetit' ), $content->path );
					$block ['content'] = $content->teaser . '<br>' . l ( 'Read more', $content->path );
					break;
				case 6 :
					$block ['subject'] = 'Facebook Like';
					$block ['content'] = "<fb:like-box profile_id='121764281183650' width='192' stream='false' header='false'></fb:like-box>";
					break;
				case 7 :
					$block ['subject'] = 'Facebook Comments';
					$block ['content'] = "<fb:comments width='522'></fb:comments>";
					break;
				case 8 :
					$nid = next ( explode ( '/', $_GET ['q'] ) );
					foreach ( taxonomy_get_vocabularies () as $vocab )
						if ($vocab->name == 'Section')
							$vid = $vocab->vid;
					foreach ( node_load ( $nid )->taxonomy as $term )
						if ($term->vid == $vid)
							$tid = $term->tid;
					$nodes = taxonomy_select_nodes ( array ($tid ) );
					$html = null;
					$test_fn = get_class ( $nodes ) == 'mysqli_result' ? 'mysqli_fetch_object' : 'mysql_fetch_object';
					while ( $node = call_user_func ( $test_fn, $nodes ) )
						if ($nid != $node->nid) {
							$node = node_load ( $node->nid );
							$html .= '<li>' . l ( $node->title, $node->path ) . '</li>';
						}
					$html = "<ul>$html</ul>";

					$block ['subject'] = 'Previous Articles';
					$block ['content'] = $html;
					break;
				case 9 :
					$nid = next ( explode ( '/', $_GET ['q'] ) );
					foreach ( taxonomy_get_vocabularies () as $vocab )
						if ($vocab->name == 'Issue')
							$vid = $vocab->vid;
					foreach ( node_load ( $nid )->taxonomy as $term )
						if ($term->vid == $vid)
							$tid = $term->tid;
					$nodes = taxonomy_select_nodes ( array ($tid ) );
					$html = null;
					$test_fn = get_class ( $nodes ) == 'mysqli_result' ? 'mysqli_fetch_object' : 'mysql_fetch_object';
					while ( $node = call_user_func ( $test_fn, $nodes ) )
						if ($nid != $node->nid) {
							$node = node_load ( $node->nid );
							$html .= '<li>' . l ( $node->title, $node->path ) . '</li>';
						}
					$html = "<ul>$html</ul>";

					$block ['subject'] = 'Other Articles';
					$block ['content'] = $html;
					break;
			}
			return $block;
	}
	return $op->content;
}

function bg_section($section) {
	$section = str_replace ( '-', ' ', $section );
	drupal_goto ( bg_get_article ( $section )->path );
}

function bg_archives($issue = false) {
	return bg_get_article ( 'Cover Story', $issue )->teaser;
}

function bg_archivelist() {
	$html = null;
	$timeline = time () - 60 * 60 * 24 * 30;
	$filename = 'sites/default/files/cover-' . strtolower ( date ( 'F-Y', $timeline ) ) . '.jpg';
	$alt = true;
	while ( file_exists ( $filename ) ) {
		$month = date ( 'F Y', $timeline );
		if ($alt)
			$html .= "<tr>";
		$html .= "<td style='text-align: center;'><a href='archives/$month'><img src='$filename'></a></td>";
		if (! $alt)
			$html .= "</tr>";
		$alt = ! $alt;
		$timeline -= 60 * 60 * 24 * 30;
		$filename = 'sites/default/files/cover-' . strtolower ( date ( 'F-Y', $timeline ) ) . '.jpg';
	}
	return "<table>$html</table>";
}

function bg_gallery() {
	return "";
}

function bg_etc() {
	return "";
}

function bg_about() {
	return "";
}

