<?php

function crossword_menu()
{
/*	$items['admin/settings/crossword/new'] = array(
		'title' => 'Crossword settings',
		'description' => 'Create a new crossword.',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('crossword_admin_settings'),
		'access arguments' => array('administer site configuration'),
		'type' => MENU_NORMAL_ITEM,
		'file' => 'crossword.admin.inc',
	);
*/	
	$items['crosswords/show/%'] = array(
		'page callback' => 'show_crossword',
		'page arguments' => array(2),
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);

	return $items;
}

function show_crossword($id = 0)
{
	$rel_path = '';
	$clues_config = null;
	$crossword = db_fetch_object(db_query("SELECT * FROM {crosswords} WHERE id = %d", $id));
	$clues = db_query("SELECT * FROM {crossword_clues} WHERE crossword_id = %d", $id);
	while($clue = db_fetch_object($clues))
		$clues_config .= "new oyCrosswordClue(" . strlen($clue->answer) . ", '$clue->clue', '', '" . 
											md5($crossword->id . $clue->answer) . "', $clue->sign, $clue->xpos, $clue->ypos),";

	$js = "if (!oygInit){ 
			alert(\"There was an error requesting puzzle data from the server.\\n\" + 
				\"Please try again shortly or send us a note about the problem.\");
		} else {
			var oygCrosswordPuzzle = new oyCrosswordPuzzle (
			  '$crossword->id','$rel_path','/a/a',
			  '$crossword->title','$crossword->description',
			  [ $clues_config ], $crossword->width, $crossword->height
			);
	
			oygCrosswordPuzzle.publisherName = '';
			oygCrosswordPuzzle.publisherURL = 'http://www.businessgoa.net';
			oygCrosswordPuzzle.leaveGameURL = 'http://www.businessgoa.net'; 
			oygCrosswordPuzzle.canTalkToServer = false;
			oygBind(oygCrosswordPuzzle);
		}";
	
	drupal_add_js($js, 'inline', 'footer');
	drupal_add_js(drupal_get_path('module', 'crossword').'/oy-cword-1.0/js/oyPrologue.js', 'module', 'footer');
	drupal_add_js(drupal_get_path('module', 'crossword').'/oy-cword-1.0/js/oyJsrAjax.js', 'module', 'footer');
	drupal_add_js(drupal_get_path('module', 'crossword').'/oy-cword-1.0/js/oyClue.js', 'module', 'footer');
	drupal_add_js(drupal_get_path('module', 'crossword').'/oy-cword-1.0/js/oyMenu.js', 'module', 'footer');
	drupal_add_js(drupal_get_path('module', 'crossword').'/oy-cword-1.0/js/oyPuzzle.js', 'module', 'footer');
	drupal_add_js(drupal_get_path('module', 'crossword').'/oy-cword-1.0/js/oyServer.js', 'module', 'footer');
	drupal_add_js(drupal_get_path('module', 'crossword').'/oy-cword-1.0/js/oySign.js', 'module', 'footer');
	drupal_add_js(drupal_get_path('module', 'crossword').'/oy-cword-1.0/js/oyMisc.js', 'module', 'footer');
	drupal_add_css(drupal_get_path('module', 'crossword').'/oy-cword-1.0/css/base.css', 'module');
	
	return "<div id='oygContext' align='center' style='width:100%;'>
		<table class='oyOuterFrame' border='0' cellpadding='0' cellspacing='0'>
			<tr><td align='center'>
				<table class='oyFrame' border='0' cellpadding='0' cellspacing='0'>
					<tr>
						<td colspan='5'>
							<table class='oyFrame' border='0' cellpadding='0' cellspacing='0' width='100%'>
								<tr class='oyHeader'>
									<td class='oyHeader'>
										<div id='oygHeader'></div>
									</td>
									<td align='right'>	
										<div id='oygHeaderMenu'></div>								
									</td> 
								</tr>					
							</table>
						</td>  
					</tr>
					<tr style='height: 4px;'>
						<td colspan='5'></td>
					</tr>
					<tr>  
						<td rowspan='3' class='oyPuzzleCell' align='center' valign='top'> 
							<div id='oygState'></div>
							<div class='oyPuzzle' id='oygPuzzle'></div>
							<div class='oyPuzzleFooter' id='oygPuzzleFooter'></div>			
						</td>  
						<td class='oyListCellDot'>.</td>    
						<td class='oyListCell' valign='top' id='oygListH'></td>
					</tr>
					<tr style='height: 4px;'>
						<td colspan='4'></td>
					</tr>		
					<tr>  
						<td class='oyListCellDot'>.</td>   
						<td class='oyListCell' valign='top' id='oygListV'></td>					
					</tr>
					<tr style='height: 4px;'>
						<td colspan='5'></td>
					</tr>			
					<tr>
						<td colspan='5' class='oyFooter'> 
							<div id='oygFooter'></div>
						</td>
					</tr>			
				</table>
			</td></tr>
		</table>
		<div id='oygStatic' align='center' style='font-size: 10px; color: #4282B5; font-family: Arial;'></div>
	</div>";
}